# 模型继续训练的参数
train_algo: {value: ["default"], distribution: choice}  # 选择网络模型结构
num_classes: {value: [2], distribution: choice}  # 分类类别数

#m_update__conv1_drop: {value: [0.0, 0.4], distribution: uniform}  # 第一个卷积层dropout概率
#m_update__conv2_drop: {value: [0.0, 0.4], distribution: uniform}  # 第二个卷积层dropout概率
#m_update__fc1_drop: {value: [0.0, 0.4], distribution: uniform}  # 第一个全连接层dropout概率
#m_update__fc2_drop: {value: [0.0, 0.4], distribution: uniform}  # 第二个全连接层dropout概率
#m_update__fc3_drop: {value: [0.0, 0.4], distribution: uniform}  # 第三个全连接层dropout概率

lr_algo: {value: ["adam"], distribution: choice}  # 优化器算法
lr_weight_decay: {value: [0.0001, 0.001], step: 0.0001, distribution: quniform}  # 权重衰减
lr: {value: [0.00001, 0.0001], step: 0.00001, distribution: quniform}  # 默认学习率, 如果下面的层不指定，则使用默认学习率. 参数必须

lr_scheduler_algo: {value: ["reducelr"], distribution: choice}  # 优化器调度器算法, none表示不用
steplr_step_size: {value: [30], distribution: choice}  # 学习率衰减周期, 仅在algo为steplr时有效
steplr_gamma: {value: [0.1], distribution: choice}  # 学习率衰减因子, 仅在algo为steplr时有效
reducelr_mode: {value: ["min"], distribution: choice}  # 学习率调度模式, 仅在algo为reducelr时有效

loss_func: {value: ["cross_entropy"], distribution: choice}  # 损失函数
loss_weights: {value: ["1"], distribution: choice}  # 初始损失函数权重.

batch_size: {value: [10, 20, 30, 40, 50], distribution: choice}  # 批大小
#num_epochs: {value: [20, 50, 100, 200, 500, 1000], distribution: choice}  # 训练周期
num_epochs: {value: [2], distribution: choice}  # 训练周期
early_stop_strategy: {value: ["R01B_acc,30,max,0.01"], distribution: choice}  # 早停指标
output_metric: {value: ["Valid_acc_0_max|R01B_acc_0_max"], distribution: choice}  # 早停指标
